"""add project employee assignments

Revision ID: 4c56cb063318
Revises: 27c006387452
Create Date: 2026-09-09 14:37:13.908109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c56cb063318'
down_revision: Union[str, Sequence[str], None] = '27c006387452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_employee_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_employee_assignments_employee_id'), 'project_employee_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_project_employee_assignments_id'), 'project_employee_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_project_employee_assignments_project_id'), 'project_employee_assignments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_employee_assignments_project_id'), table_name='project_employee_assignments')
    op.drop_index(op.f('ix_project_employee_assignments_id'), table_name='project_employee_assignments')
    op.drop_index(op.f('ix_project_employee_assignments_employee_id'), table_name='project_employee_assignments')
    op.drop_table('project_employee_assignments')
    # ### end Alembic commands ###
