"""add employee id to notifications

Revision ID: 4eff956d54d9
Revises: f0daf58b9fb0
Create Date: 2026-09-09 17:14:24.674148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eff956d54d9'
down_revision: Union[str, Sequence[str], None] = 'f0daf58b9fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_employee_id'), 'notifications', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_employee_id'), table_name='notifications')
    op.drop_column('notifications', 'employee_id')
    # ### end Alembic commands ###
