"""add work report projects

Revision ID: d716b0d0a568
Revises: 4eff956d54d9
Create Date: 2026-09-12 15:52:26.658568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd716b0d0a568'
down_revision: Union[str, Sequence[str], None] = '4eff956d54d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_report_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_report_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_report_id'], ['work_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_report_projects_id'), 'work_report_projects', ['id'], unique=False)
    op.create_index(op.f('ix_work_report_projects_project_id'), 'work_report_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_report_projects_work_report_id'), 'work_report_projects', ['work_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_report_projects_work_report_id'), table_name='work_report_projects')
    op.drop_index(op.f('ix_work_report_projects_project_id'), table_name='work_report_projects')
    op.drop_index(op.f('ix_work_report_projects_id'), table_name='work_report_projects')
    op.drop_table('work_report_projects')
    # ### end Alembic commands ###
