"""create work reports table

Revision ID: da764dcb7bc5
Revises: be22cd7836a2
Create Date: 2026-09-05 14:39:34.407948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da764dcb7bc5'
down_revision: Union[str, Sequence[str], None] = 'be22cd7836a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('work_description', sa.Text(), nullable=False),
    sa.Column('tasks_completed', sa.Text(), nullable=True),
    sa.Column('hours_worked', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('performance_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_reports_employee_id'), 'work_reports', ['employee_id'], unique=False)
    op.create_index(op.f('ix_work_reports_id'), 'work_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_reports_id'), table_name='work_reports')
    op.drop_index(op.f('ix_work_reports_employee_id'), table_name='work_reports')
    op.drop_table('work_reports')
    # ### end Alembic commands ###
